/* A closing section per industry: what the first conversation covers, how the
   engagement usually runs, and the honest caveat. */

const IND_CLOSE = {
restaurants: ['The first conversation is about covers and orders rather than colours. How busy are the quiet nights, what share of ordering is direct versus through an app, and which of those numbers you actually want to move.','From there the work is usually staged. The menu, hours and booking path first, because those produce the fastest change. Photography, local search and any direct ordering after that, once the foundation is carrying its weight.','The honest caveat is that a website will not fix a quiet restaurant on its own. It removes friction for people already deciding about you. If nobody is deciding, the problem is upstream of the site and worth saying so.'],

'real-estate': ['The first conversation is about listing data: which board, what feed access exists, and what you are permitted to display. That determines what can be built before anything else is discussed.','The build then usually runs in two parts. Listings structured properly so every property has a real page, then neighbourhood and area content that keeps working between transactions.','The honest caveat is that listing pages alone rarely rank for competitive terms. The compounding value is in area content, and that takes months rather than weeks to show results.'],

'trades-and-home-services': ['The first conversation is about calls: how many you take, where they come from now, and which services you actually want more of. Trades sites often rank for the wrong work and turn away the profitable jobs.','The build is usually straightforward and fast. Split the services page, add area pages, make the phone unmissable, and cut the page weight so the site holds up in a spike.','The honest caveat is that local search is a fight you win over months, not days. Google Business Profile work moves first, and organic service pages follow behind it.'],

'healthcare-and-clinics': ['The first conversation is about what the site is allowed to do. Privacy obligations and accessibility requirements set the boundaries before design begins, and discovering them late is expensive.','From there the work is usually patient-facing clarity first, new patient status, coverage, hours, location, followed by any directory or booking integration.','The honest caveat is that healthcare projects move at the speed of their approvals. Where a board or privacy officer has to sign off, that is the real timeline and it is worth planning around.','One more thing worth saying plainly: the biggest measurable win on most clinic sites is reducing phone calls to reception. Every question the website answers clearly, about new patients, coverage, parking, hours, is a call somebody does not have to take. That is a direct operational saving, it improves the patient experience, and it is far easier to demonstrate than an abstract improvement in brand perception.'],

'professional-services': ['The first conversation is about who you want to hear from, and just as importantly who you do not. Professional services sites frequently attract enquiries the firm would rather decline.','The work is then mostly structural and editorial: splitting broad categories into specific situations, and building content that demonstrates expertise rather than asserting it.','The honest caveat is patience. This is one of the slower sectors to show results, because the buying cycle itself is long. The trade-off is that each enquiry tends to be worth considerably more.','One more thing worth saying plainly: the firms that do best from their websites are the ones willing to be specific in public. Naming the situations you handle, the sizes of client you suit and the work you decline attracts better enquiries and fewer wasted calls. It feels counterintuitive to narrow the message, and it is consistently the change that improves enquiry quality most in this sector.'],

construction: ['The first conversation is about which work you want more of. Residential and commercial pull in different directions, and a site trying to serve both equally usually serves neither well.','The build centres on project pages with real photography, then the qualification material that commercial buyers check before anything else, and a careers section if hiring matters.','The honest caveat is that photography is the constraint. Without real images of real projects, a construction site cannot do its main job, and no amount of design compensates for that.','One more thing worth saying plainly: the single biggest constraint on a construction website is almost never the budget, it is photography. Sites in this sector live or die on whether a prospective client can see work comparable to their own, and no amount of layout, copy or technical quality substitutes for that. If good photographs of completed projects do not exist yet, commissioning them is usually a better first investment than the website itself.'],

'ecommerce-and-retail': ['The first conversation is about the funnel: traffic, add-to-cart, checkout completion. Those three numbers tell you immediately whether the problem is attracting people or losing them.','Most stores are losing them, which means checkout and page speed come before any traffic work. Spending on ads to fill a leaking funnel is the most common expensive mistake in ecommerce.','The honest caveat is that speed and checkout work have a ceiling. Once the store converts properly, further growth comes from traffic and merchandising, which is a different and ongoing kind of effort.','One more thing worth saying plainly: most stores that ask for more traffic actually need better conversion. Doubling visitors to a checkout that loses two thirds of them costs real money and produces a fraction of the return that fixing the checkout would. It is worth establishing which problem you have before committing budget, because the answer changes what should be built and in what order.'],

'publishing-and-media': ['The first conversation is about where your readers actually come from now, and how exposed that is. Publishers who depend on a single referral channel are carrying a risk they often have not priced.','The work then splits between performance, keeping archives and article pages fast at volume, and workflow, because minutes saved per article compound quickly at publishing frequency.','The honest caveat is that no technical work replaces editorial judgement. A fast site helps good journalism find readers; it does not create the readership on its own.','One more thing worth saying plainly: performance on a publishing site degrades quietly. Every new ad partner, tracking script and embedded widget adds weight, and because it accumulates gradually nobody notices until rankings and engagement have already moved. Treating page weight as something monitored continuously, rather than fixed once at launch, is the difference between a site that stays fast and one that has to be rescued every two years.'],

'nonprofits-and-associations': ['The first conversation is about where volunteer and staff time currently goes. Most nonprofit websites carry hidden administrative cost that automation removes permanently.','The build usually prioritises the donation flow and any membership or event administration, because those produce measurable return, then transparency and accessibility work.','The honest caveat is budget. Nonprofit projects are frequently constrained, and the right answer is often to do the two highest-return things properly rather than everything cheaply.','One more thing worth saying plainly: the most valuable work on a nonprofit site is frequently invisible from the outside. Automating renewals, registrations and receipting does not change how the site looks, and it removes hours of volunteer and staff time every month permanently. When budget is limited, that operational saving usually compounds faster than a visual refresh, and it is worth weighing the two honestly rather than assuming a redesign is the priority.'],

'manufacturing-and-industrial': ['The first conversation is about the buyer: who specifies, who purchases, who approves, and what each of them needs to see before your product is shortlisted.','The work then centres on making specifications and certifications genuinely findable, and restructuring the catalogue so it can be filtered by the attributes buyers search on.','The honest caveat is that industrial sales cycles are long and involve people who never fill in a form. Measuring success by enquiries alone will undercount what the site is actually doing.','One more thing worth saying plainly: industrial websites are usually judged by the wrong people inside the business. Sales looks at enquiry volume, marketing looks at traffic, and neither number captures the engineer who downloaded a datasheet, specified your part into a drawing and never identified themselves at any point. If the site is going to be assessed fairly, agree beforehand what counts as a result, and make sure specification-stage behaviour is part of that definition rather than an afterthought nobody reports on.']
};

module.exports = { IND_CLOSE };
