/* What to measure per industry. Specific metrics beat generic "traffic". */

const IND_MEASURE = {
restaurants: ['The number worth watching is not traffic, it is booking clicks and direct orders. A restaurant site can double its visitors and change nothing about the business if none of them reach the booking step.','Track the path from menu view to reservation or order, and watch it separately on mobile, since that is where nearly all of the audience is. If mobile converts at half the desktop rate, that gap is the whole project.','Map impressions and calls from the Google Business Profile belong in the same report. For most restaurants those numbers move before anything on the website does.'],

'real-estate': ['Measure enquiries per listing rather than total site traffic. A portal-sized visitor count means little if the properties themselves are not generating contact.','Watch which listing pages receive organic search traffic, because those tell you what buyers are actually searching for, often a neighbourhood or building name rather than a price bracket.','Neighbourhood content should be measured on a longer horizon. It accumulates slowly and then keeps producing, so judging it after a month will always look like failure.'],

'trades-and-home-services': ['Calls are the metric. Track tap-to-call events separately from form submissions, because for urgent work the phone is where the money is and form counts will understate performance badly.','Watch performance by service and by area, not in aggregate. A site can look healthy overall while the profitable services quietly bring in nothing.','Seasonal comparison has to be year over year rather than month to month. Comparing February to January in this sector tells you about the weather, not about the website.'],

'healthcare-and-clinics': ['The most useful measure is often a reduction in reception calls asking questions the site should answer. That is a direct operational saving and it is easy to observe.','Track booking completions and where people abandon. A booking flow that loses patients at a particular step is usually fixable once the step is identified.','Traffic to the practitioner directory and to specific service pages tells you what patients are actually looking for, which frequently differs from what the clinic assumes.'],

'professional-services': ['Measure enquiry quality, not enquiry count. A page that produces four well-matched enquiries beats one producing thirty that all get declined.','Attribution has to survive a long gap. Somebody may read three articles in March and make contact in July, and last-click reporting will credit that to a direct visit and hide what actually worked.','Watch time on the substantive pages. In this sector, people who read carefully before contacting are the ones who become clients.'],

construction: ['Separate residential and commercial enquiries in reporting. They have completely different values and mixing them produces an average that describes neither.','Track which project pages get read before an enquiry arrives. That tells you which work to photograph and document next.','Applications through the careers section belong in the same report. For many contractors that channel is worth as much as the client enquiries.','Finally, watch how long the gap is between a first visit and an enquiry. Construction buyers frequently return three or four times over several weeks before they make contact, and a report that treats each of those visits as a separate anonymous session will make a site that is working look like one that is not.'],

'ecommerce-and-retail': ['Conversion rate by device is the number that matters most, because mobile and desktop frequently differ by a factor that would be alarming if anyone looked.','Watch checkout abandonment step by step. Knowing that people leave at shipping is actionable; knowing that carts are abandoned is not.','Revenue per visitor is a better headline than conversion rate alone, since it accounts for average order value and stops you optimising toward cheaper baskets.'],

'publishing-and-media': ['Measure pages per session and returning readers rather than raw pageviews. A publisher with loyal readers is worth far more than one with a viral spike.','Track which articles bring people in from search, and how many of those readers go on to a second article. That second click is where a visitor becomes an audience.','Watch Core Web Vitals continuously rather than occasionally, because on a site publishing daily, performance degrades gradually and nobody notices until rankings move.'],

'nonprofits-and-associations': ['Measure donation completion rate, not just total raised. A campaign that drives plenty of traffic to a form people abandon is a fixable problem hiding behind a disappointing total.','Track recurring versus one-time giving separately. Recurring donors are worth several times a single gift and are almost always under-promoted.','Membership renewals and event registrations belong in the same view, since for many associations those are the operational numbers the website most affects.'],

'manufacturing-and-industrial': ['Datasheet downloads and specification page views often matter more than form submissions, because technical buyers research long before they identify themselves.','Track which product families attract search traffic. That is genuine market signal about what buyers are looking for and it frequently surprises the sales team.','Accept that attribution will be incomplete. Industrial buying involves people who never fill in a form, so judging the site on enquiry count alone will undercount it substantially.']
};

module.exports = { IND_MEASURE };
